---
title: "Example for Diana"
author: "Juliane Gaviraghi Mussoi"
date: "2025-05-12"
output: html_document
---


```{r}
library(factoextra)

```

# Effects of sleep disturbances on call spectral parameters

## Analysis and Visualisation

```{r, warning= FALSE, message= FALSE}
#correlation matrix to see which variables are highly correlated with each other
sp_cor<- cor(sp[,c(3:28, 30,31)], use = "complete.obs")
sp_cor[lower.tri(sp_cor)] <- 0

#chose variables lower than 0.6 correlation: "duration", "meanfreq", "kurt", "time.ent", "entropy", "dfrange", "modindx", "startdom", "dfslope"

#making pca with spectro analysis data (<0.6 correlation)
sp.pca <- prcomp(sp[,c("duration", "meanfreq", "kurt", "time.ent", "entropy", "dfrange", "modindx", "startdom", "dfslope")], center = TRUE,scale. = TRUE,tol = 0.1)

summary(sp.pca)
sp.pca

#this generates the PC scores for each recordings
axes_sp_pca <- predict(sp.pca, newdata = sp)
#making sure it worked
head(axes_sp_pca, 4)
#creating a new dataframe that adds the the PC scores to the end
df_sp_pca <- cbind(sp, axes_sp_pca)

```


```{r message=FALSE, warning=FALSE}
fviz_eig(sp.pca,addlabels = TRUE) #scree plot

eig.val <- get_eigenvalue(sp.pca) #getting eighvalue from each pca
eig.val

pca.var<- get_pca_var(sp.pca)
pca.var$contrib
pca.var$coord
pca.var$cos2


# % contribution of the variables 
fviz_pca_var(sp.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)

```

